In [1]:
import torch
print(torch.__version__)

1.7.1


### 自动求导机制

In [2]:
x = torch.randn(4,1, requires_grad=True)
y = torch.randn(4,1, requires_grad=True)
W = torch.randn(4,4)
print(x)
print(y)
print(W)

tensor([[-1.4823],
        [ 0.6876],
        [ 0.7771],
        [-0.5657]], requires_grad=True)
tensor([[ 1.2365],
        [-0.6623],
        [ 0.4708],
        [-1.0414]], requires_grad=True)
tensor([[ 1.0993e+00, -3.3742e+00,  7.4155e-01,  5.0608e-01],
        [-1.6634e+00, -1.6936e+00,  4.3405e-02, -1.9466e-04],
        [ 2.7807e+00,  2.4988e-01,  5.6594e-01, -6.2502e-01],
        [-1.5817e+00,  9.7928e-01, -1.0865e-01,  2.6080e-01]])


In [3]:
z = torch.mm(torch.mm(torch.t(x), W),y)
print(z)

tensor([[-0.7805]], grad_fn=<MmBackward>)


In [4]:
z = x.t().mm(W).mm(y).abs()
print(z)

tensor([[0.7805]], grad_fn=<AbsBackward>)


In [5]:
print(x.grad)

None


In [6]:
z.backward()

In [7]:
print(x.grad)

tensor([[-3.4161],
        [ 0.9145],
        [-4.1900],
        [ 2.9270]])


In [8]:
print(W.mm(y))

tensor([[ 3.4161],
        [-0.9145],
        [ 4.1900],
        [-2.9270]], grad_fn=<MmBackward>)


### 默认情况下，定义的tensor属性requires_grad为false

In [9]:
x = torch.randn(4,1)
print(x)
y = torch.mm(torch.t(x),x)
y.backward()

tensor([[-0.5816],
        [ 1.7835],
        [-1.0958],
        [-0.4035]])


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [10]:
print(y)

print(x.grad)

print(2*x)

tensor([[4.8826]])
None
tensor([[-1.1632],
        [ 3.5670],
        [-2.1916],
        [-0.8069]])


### PyTorch Tensor 与 Numpy 转换

In [11]:
import numpy as np
import torch

a = np.random.randn(3,4)
print(a)
print(type(a))

[[ 0.32617615 -0.03157882  1.93448791  1.09613401]
 [-1.2275926  -0.49364708  1.72482642  1.08428308]
 [ 1.7128044  -0.79749733  0.43768984  0.18220911]]
<class 'numpy.ndarray'>


In [12]:
a_tensor = torch.from_numpy(a)
print(a_tensor)
print(type(a_tensor))

tensor([[ 0.3262, -0.0316,  1.9345,  1.0961],
        [-1.2276, -0.4936,  1.7248,  1.0843],
        [ 1.7128, -0.7975,  0.4377,  0.1822]], dtype=torch.float64)
<class 'torch.Tensor'>


In [13]:
b = a_tensor.numpy()
print(b)
print(type(b))

[[ 0.32617615 -0.03157882  1.93448791  1.09613401]
 [-1.2275926  -0.49364708  1.72482642  1.08428308]
 [ 1.7128044  -0.79749733  0.43768984  0.18220911]]
<class 'numpy.ndarray'>


In [14]:
d_tensor = torch.randn(3, 4, requires_grad=False)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

[[ 0.9161768   1.0006001  -0.45008767 -1.2464808 ]
 [-0.8147663   0.14001296 -1.7301487   1.052789  ]
 [-0.6071614   1.1650263   0.92801154  0.51560754]]
<class 'numpy.ndarray'>


In [15]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [16]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.data.numpy()
print(d_numpy)
print(d_tensor.data)
print(type(d_numpy))

[[ 0.11759191 -1.1422616   1.1180165   0.18604757]
 [-0.07143331 -0.26128447 -1.170119   -1.4293646 ]
 [-1.3790752  -0.9434595   0.69783103  0.19119696]]
tensor([[ 0.1176, -1.1423,  1.1180,  0.1860],
        [-0.0714, -0.2613, -1.1701, -1.4294],
        [-1.3791, -0.9435,  0.6978,  0.1912]])
<class 'numpy.ndarray'>
